# Generated by Django 4.2.6 on 2023-10-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_app_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='repoLink',
        ),
        migrations.AddField(
            model_name='app',
            name='repoLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
