# Generated by Django 4.2.6 on 2023-11-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_tagstring_tag_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='ddd', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
