# Generated by Django 4.2.6 on 2023-11-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarPath',
            field=models.CharField(blank=True, default='https://u.cubeupload.com/dawid8374/genericavatar.png', max_length=255, null=True),
        ),
    ]
