# Generated by Django 4.2.6 on 2023-11-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_user_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
