# Generated by Django 4.2.6 on 2023-11-29 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 29, 17, 23, 23, 171659)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 29, 17, 23, 30, 139149)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 29, 17, 23, 33, 35246)),
            preserve_default=False,
        ),
    ]
