# Generated by Django 4.2.6 on 2023-10-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_entry_repolink_app_repolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('TYPE1', 'Bug'), ('TYPE2', 'Feature suggestion')], default='TYPE1', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NEW', max_length=50),
        ),
    ]
